CREATE TABLE IF NOT EXISTS refresh_tokens (
  id           INT AUTO_INCREMENT PRIMARY KEY,
  token_hash   VARCHAR(255) NOT NULL UNIQUE,
  user_id      INT NOT NULL,
  expires_at   DATETIME NOT NULL,
  revoked      BOOLEAN NOT NULL DEFAULT FALSE,
  persistent   BOOLEAN NOT NULL DEFAULT FALSE,
  created_at   DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id)
);
